import './globals.css'
import { Toaster } from '@/components/ui/toaster';

export const metadata = {
  title: 'ARSDEV.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='scroll-smooth' lang="en">
      <body>
           {children}
           <Toaster/>
      </body>
    </html>
  )
}
